FROM node:18-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY package*.json ./

COPY prisma ./prisma/

RUN npm install

RUN npx prisma generate

COPY . .

RUN mkdir -p uploads

EXPOSE 8000 9229

CMD ["npm", "run", "dev:debug"]